//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor_AGV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGV_ErrorHistory
    {
        public int ID { get; set; }
        public int ID_AGV { get; set; }
        public Nullable<System.DateTime> TimerError { get; set; }
        public Nullable<int> ErrorCode { get; set; }
    }
}
